server:
  port: 7000
spring:
  cloud: 
    gateway:
      routes:
        - id: serv-vuelos
          uri: lb://servicio-vuelos
          predicates:
            - Path=/svuelos/**
          filters:
            - RewritePath=/svuelos/(?<segment>.*), /$\\{segment}
            
        - id: serv-hoteles
          uri: lb://servicio-hoteles
          predicates:
            - Path=/shoteles/**
          filters:
            - RewritePath=/shoteles/(?<segment>.*), /$\\{segment}
            
        - id: serv-reservas
          uri: lb://servicio-reservas
          predicates:
            - Path=/sreservas/**
          filters:
            - RewritePath=/sreservas/(?<segment>.*), /$\\{segment}
            
        - id: serv-auth
          uri: lb://servicio-auth
          predicates:
            - Path=/sauth/**
          filters:
            - RewritePath=/sauth/(?<segment>.*), /$\\{segment}
    
eureka:                  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
